sudo: true # Puppeteer doesn't work in the container based builds
language: node_js
node_js:
  - "8"
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install --frozen-lockfile
